### ISSUE TITLE
Adding support for NumPy

### ISSUE THREAD

**Issue by AndreFrelicot** [pybee/Python-iOS-support#11]
Hello, can I add NumPy to the compilation ? Much like the it is done in Kivy through Recipes. I see you use recipes on the Android support, why not in the iOS support ?

thank you

**Comment by freakboy3742** [comment]
The Android build uses recipes because I started with their build process. However, I've largely abandoned that project, because I'm no longer convinced that CPython+JNI is the best approach for Android. I'm working on an alternative, but there's nothing ready yet.

I'm not opposed to adding a recipe-like infrastructure to the iOS build; I just haven't had the need for it myself. As long as you can set up the infrastructure so that NumPy is a completely optional part of the build, I'd happily merge a patch for this.

However, in the case of something like Numpy, I'd also be interested in seeing if it could be handled as a completely separate project - that is, a "NumPy-ios-support" package that *just* compiles a NumPy.framework, which you can include in your Python iOS project alongside Python.framework. Given that it ships as a completely standalone project, I don't see why it needs to be compiled into the *Python.framework*; surely it just needs to have Python.framework as a dependency?

I will admit, however, that I have almost no experience with NumPy, so if I'm completely wrong on this, please let me know.

**Comment by AndreFrelicot** [comment]
Thank you for the reply, I'll do some research.

**Comment by hadesh** [comment]
Hello，is there any conclusion about this？Adding NumPy work with Python.framework.

**Comment by freakboy3742** [comment]
@hadesh Well, the conclusion is "yes, it needs to be done".
