### ISSUE TITLE
Can't build libpython 2.7.1 for arm64

### ISSUE THREAD

**Issue by 4ntoine** [pybee/Python-iOS-support#17]
Actually i can't build libffi and it prevents from building libpython:
here is build logfile: https://gist.github.com/4ntoine/6f1d719083accee1e86b

**Comment by freakboy3742** [comment]
This is a known problem with libffi - you'll need to replace libffi-3.0.13 with a recent version of libffi's trunk. 

I've stopped working on the 2.7 branch; the 3.4 branch is much more robust.

**Comment by 4ntoine** [comment]
Thank for clarification! Honestly i have lot's of py files in my iOS app and i'm using libpython 2.7.1 and i'm afraid of moving to python 3.4 to have some incompatibilities of hidden errors. Any change you merge changes to 2.7.1 branch? If not, could you please explain in more details how can i replace libffi (just change version in some script?). Thanks

**Comment by freakboy3742** [comment]
If it was a simple merge, I would; but it isn't. My 3.4 branch is a from-scratch piece of work, and the changes won't just apply. Even the build process is completely different.

My honest suggestion - if you're building for mobile, it's green-fields, new development, so the only big reason to stick with 2.7 (a legacy codebase) doesn't exist. The "Incompatibilities" are resolved for all the big software that is out there. I'd give serious thought to whether it would be better to start with 3.4, rather than 2.7.

I'm not intending to backport what I've done for 3.4 to 2.7. However, I'll certainly merge any patch provided. If someone wants to pay me, that might change my mind as well :-)

**Comment by freakboy3742** [comment]
Thanks to some funding from the author of Pythonista, I've resolved this in the new Python-Apple-support package, which merges iOS, tvOS and macOS support into a single package.
