### ISSUE TITLE
Is there a pybee-based Python app available on the App-store today?

### ISSUE THREAD

**Issue by sschaetz** [pybee/Python-iOS-support#22]
Is there an app today that has gone through the app-store process and is available for download today from the app store?

**Comment by freakboy3742** [comment]
Unfortunately, not at present. 

However, there is precedent for having apps that use Python in the same way that BeeWare does - the approach used by BeeWare is the same as that used by Kivy, and Kivy *does* have apps in the app store. So - while there aren't any BeeWare apps in the app store, there is reason to believe they won't be rejected.

Closing this ticket because there's nothing directly actionable (other than submitting something to the app store, which isn't strictly a BeeWare issue - it's something that a BeeWare user will need to do at some point in the future).
