### ISSUE TITLE
arm64 support?

### ISSUE THREAD

**Issue by magin** [pybee/Python-iOS-support#3]

**Comment by sniderbr** [comment]
I think I have this working in a fork of your master branch.  I updated libffi to version 3.2.1 and replaced armv7s with arm64 and am successfully building ffi.framework and Python.framework with all 3 slices as expected.  Interested in a pull request?

**Comment by freakboy3742** [comment]
Definitely interested - I've been working on an update for Python 3.4.2 update; this almost works except for a problem with dlload on arm64 that I'm still trying to debug. If you're able to shed some light on this with a PR, I'd certainly appreciate the help.

**Comment by sniderbr** [comment]
Great, I still need to do some testing on-device but will send you the PR when done.  In the meantime, my work is here:  https://github.com/sniderbr/Python-iOS-support/tree/libffi-3.2.1+arm64

**Comment by freakboy3742** [comment]
Thanks. In particular, I'm interested in ctypes testing - this is where I'm stuck at the moment. FFI calls are working... until they don't, and I get a segfault. I'm not sure if that's my specific example and it's a legit segfault, or if there's an underlying problem that is due to libffi misconfiguration. I
