### ISSUE TITLE
Python building with ssl

### ISSUE THREAD

**Issue by alex-v1981** [pybee/Python-iOS-support#8]
How can we build python with ssl support?
(because in the python script, we get an error:  "ImportError: No module named _ssl")

**Comment by freakboy3742** [comment]
At present, there isn't an easy way to turn on SSL support. It's on my todo list, but it's non-trivial because it requires a third-party dependency (an iOS SSL library). 

If you want to tackle this, the process will be much the same as the tooling for libffi, except using the OpenSSL sources (or equivalent).

**Comment by alex-v1981** [comment]
We have prebuilt universal openssl binaries for iOS (headers and *.a files). What is the proper way to include them into the python build with your makefile script. 
(OpenSSL version is 1.0.1j)

**Comment by alex-v1981** [comment]
I found python-embedded project (https://github.com/albertz/python-embedded) that builds with SSL. Maybe it will help
